### PR TITLE
Update getBTC.php

### PR DESCRIPTION
**Pull request by EAWF**
Good catches!  

Bugfixes: #54

### CODE REVIEW

**Comment by Septem151** [comment]
Change `float $amount=''` to `float $amount = 0` and your build will pass.

**Comment by EAWF** [comment]
Did you make those changes, or are you waiting on me to make them...last I looked, the changes were there.

**Comment by Septem151** [comment]
> Did you make those changes, or are you waiting on me to make them...last I looked, the changes were there.

Changes have been made. Waiting for approval to squash and merge.

**Comment by EAWF** [comment]
OK, I'm good with it.

**Pull request merged**
