### PR TITLE
Key Derivation Overview Images

### PR DESCRIPTION
**Pull request by Septem151**
Added two .PNG files to "Images" folder. One image is the (extremely) simplified process of creating an address, starting with Entropy (random bits). The other image is a technical overview of each step in the simplified process in sequence.
Technical overview includes how different address types (P2PKH, P2SH-P2WPKH, & P2WPKH) are constructed, as well as how to tell which address type should be created.

### CODE REVIEW

**Comment by EAWF** [comment]
OK, I'm trying to document what I understand now about the process.  Suffice it to say that there is no hardened derivation needed for this set of tools.

**Comment by EAWF** [comment]
See https://github.com/EAWF/Bitcoin-Merchants-Toolbox/wiki for details of what I was talking about.

**Comment by Septem151** [comment]
Corrected derivation from BIP32 Root Key, as well as P2WPKH ("bc1") address derivation.
Now safe to merge.

**Comment by EAWF** [comment]
I'll accept this if you can explain to me how the depiction of the complete chain of derivation fits in with this project.
Refer to https://github.com/EAWF/Bitcoin-Merchants-Toolbox.

**Comment by EAWF** [comment]
Do we want to explain the whole derivation process, or should we simply show the derivation paths FROM the exported account-level extended public key and leave the rest of the derivation stuff to the other sites that already explain that?
My gut tells me just from the extended public key.
Your thoughts?

**Comment by Septem151** [comment]
I think that's a good idea. I'll go ahead and shorten the image to only include the final step about deriving addresses from an Extended Public Key. The changes will be made on Monday.

**Comment by Septem151** [comment]
Additional photo describing CKDpub, if necessary, can be added as well.
CKDpub

**Comment by EAWF** [comment]
> Additional photo describing CKDpub, if necessary, can be added as well.
> CKDpub

Question about the public key at the top.  How does it become 33 bytes? I thought public keys were 32 bytes?

**Comment by Septem151** [comment]
> Question about the public keys. If SHA512 delivers 64 bytes, and you split it in half for key and chain code, how is your public key winding up to be 33 bytes instead of 32 bytes? Where's the extra byte coming in?

After the HMAC-SHA512, the left half 32 bytes (I_L) is used as the private key value to create a public key denoted in [this step of BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#public-parent-key--public-child-key):
> The returned child key K_i is point(parse256(I_L)) + K_par.

I_L is scalar multiplied by the generator point G to create a point on the elliptic curve, such that the point created by I_L, called K_tweak, is created as such:
```K_tweak = I_L * G```
where G = generator point of the SECP256K1 curve (0x0279BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798)

K_tweak is then added to the original Public key K_par via Scalar Addition: `K_i = K_par + K_tweak` to create the new Child public key `K_i`. Public keys are represented in compressed form, where the first byte indicates the parity of the Y coordinate (whether it is even or odd) followed by the X coordinate (32 bytes) for a total of 33 bytes.

**Comment by EAWF** [comment]
> > Question about the public keys. If SHA512 delivers 64 bytes, and you split it in half for key and chain code, how is your public key winding up to be 33 bytes instead of 32 bytes? Where's the extra byte coming in?
> 
> After the HMAC-SHA512, the left half 32 bytes (I_L) is used as the private key value to create a public key denoted in [this step of BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#public-parent-key--public-child-key):
> 
> > The returned child key K_i is point(parse256(I_L)) + K_par.
> 
> I_L is scalar multiplied by the generator point G to create a point on the elliptic curve, such that the point created by I_L, called K_tweak, is created as such:
> `K_tweak = I_L * G`
> where G = generator point of the SECP256K1 curve (0x0279BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798)
> 
> K_tweak is then added to the original Public key K_par via Scalar Addition: `K_i = K_par + K_tweak` to create the new Child public key `K_i`. Public keys are represented in compressed form, where the first byte indicates the parity of the Y coordinate (whether it is even or odd) followed by the X coordinate (32 bytes) for a total of 33 bytes.

OK, First, AWESOME job on the flow chart (picture is worth a thousand words)!

Next, do you think that the parity bit logic/addition should be included, here? All I see from the chart is that the public key bytes are magically turning into 33 bytes from 32 bytes.

**Comment by Septem151** [comment]
> OK, First, AWESOME job on the flow chart (picture is worth a thousand words)!
> 
> Next, do you think that the parity bit logic/addition should be included, here? All I see from the chart is that the public key bytes are magically turning into 33 bytes from 32 bytes.

I think it should be implied that `Scalar Multiply` converts a 32-byte integer into a 33-byte Point/Public Key, and that `Scalar Addition` adds 2 points together. If we decide to go into more depth on `Scalar Multiply`, then it wouldn't make sense to have things such as `HMAC-SHA512` not described in depth as well.

I feel it is best to leave Elliptic Curve operations and Hash functions as an Abstraction rather than going into too much detail on it. Not to mention, it would be extremely difficult to put into flowchart form.

Also, the Address Derivation (massive image from the first commits) has been simplified to only include the last section, with some corrections and modifications to the flowchart to make it more easily readable.

**Comment by EAWF** [comment]
My feeling is that HMAC-SHA512 is fairly straight-forward as it can be easily expressed as an algebraic equation programmatically. It's a built-in function for most programming languages and that's good enough for our purposes of explaining that, "you do this" to get what you need.

With the view that our goal is to educate programmers how to create the derivation tools, can scaler math be described in a similar manner?

Are the Scaler functions built-in with most programming languages? 

Are there other requirements, such as a minimum requirement of the server or the language requiring 64bit OS support? I know that C variants, Python, PHP7, assuming Ruby, and probably others can do it, but do you know what the limitations are?

**Comment by EAWF** [comment]
Looking more at the flow chart, in the decision box, shouldn't the range of the index fall between 0 and 2^32-1 (0x00000000 - 0x7FFFFFFF)? The fail part of that decision probably won't apply as the programmer is going to have to keep track of unused address indices in a separate system and hard code the limit.

**Comment by Septem151** [comment]
Elliptic Curve Cryptography support is fairly universal.

[Comparison of Cryptography Libraries](https://en.wikipedia.org/wiki/Comparison_of_cryptography_libraries) lists 3 languages that have ECC libraries:
- [C](https://www.cs.auckland.ac.nz/~pgut001/cryptlib/)
- [C++](https://www.cryptopp.com/)
- [Java](http://bouncycastle.org/java.html)
- [Python](https://pypi.org/project/fastecdsa/)
- [Ruby](https://github.com/DavidEGrayson/ruby_ecdsa)
- [JavaScript](https://github.com/bitchan/eccrypto)
- [JavaScript with Node.js](https://www.npmjs.com/package/secp256k1)
- [C#](http://www.bouncycastle.org/csharp/)
- [PHP](https://github.com/phpecc/phpecc)

...and probably others that I am missing. It is a fairly standard library.

As for the index range, i is an unsigned int and will never be negative. Thus the equation `i < 2^31` is sufficient, since any value between `2^31 <= x < 2^32` would be a hardened index. I included this step in the diagram since it is directly referenced in the BIP.

**Comment by EAWF** [comment]
Thanks for that list of libraries.  It's clear now that the algorithm can be clipped for the ECC stuff and references made to outside resources for explanations. I think we need to include references and links where possible, and where the byte counts don't match the public keys in the image, that difference should be explained in the text surrounding the graphic.

**Pull request merged**
