### PR TITLE
Remove old-master code

### PR DESCRIPTION
**Pull request by Septem151**
Separate old-master into its own branch.

You'll see under the repo's branches, there is a branch called "old-master". This is where all the old repository's history and its files are located, prior to any changes made to restructure or re-start the repo. 

When we are ready, we can remove this old-master branch. In the meantime, there are still some files from it that I would like to keep, such as the Address-Derivation.md page and associated images that I had created. Additionally, it may help to serve as somewhat of a reference for us if we need to go back and check in it.

However, it's up to you whenever the "old-master" branch can be deleted. I have already saved my files needed. The "old-master" branch can be safely deleted at any time.

### CODE REVIEW

**Comment by EAWF** [comment]
It is going to be easy to copy and paste from the branch to the new master?

I have reconsidered and will only delete the repo when I feel completely humiliated and embarrassed with it, I think.  :smile:

**Comment by EAWF** [comment]
Noted this message above the merge pull request.

Continuous integration has not been set up
GitHub Actions and several other apps can be used to automatically catch bugs and enforce style.

Do I just do the Merge pull request now, or would it be better for you to set up continuous integration, whatever that is?

**Comment by Septem151** [comment]
We don't have continuous integration setup yet. That's what the `.github` folder is for in the other repo. It's fine to simply merge the pull request.



> It is going to be easy to copy and paste from the branch to the new master?
> 
> I have reconsidered and will only delete the repo when I feel completely humiliated and embarrassed with it, I think.

If at any time you need to use the old branch's files (for example to save a copy of it to your computer while keeping the new code as well) you can checkout the old branch:
```sh
git fetch               # makes sure your local git is up to date with the github repo
git checkout old-master
```

then do what you want with the old-master files. When finished, checkout the master branch again:
```sh
git checkout master
```

**Comment by EAWF** [comment]
OK, i get that, BUT, I'm doing most of my work online and not on the desktop. I start doing ADD type stuff, lose concentration, and then screw things up bad enough on the online version...have been catching myself working in two tabs and editing the same page too many times.

I really need to rely on the rollback features.

So, for me, what do you recommend as the best way to copy and paste stuff from the old-master to the new-master areas.  That was why I just moved it into a different folder.

**Comment by Septem151** [comment]
> OK, i get that, BUT, I'm doing most of my work online and not on the desktop. I start doing ADD type stuff, lose concentration, and then screw things up bad enough on the online version...have been catching myself working in two tabs and editing the same page too many times.
> 
> I really need to rely on the rollback features.
> 
> So, for me, what do you recommend as the best way to copy and paste stuff from the old-master to the new-master areas. That was why I just moved it into a different folder.

I don't think I understand what you mean by this. The old repo's information is always available, it's just in a separate branch called "old-master". You can have different tabs open with one on the "old-master" branch and another on the "master" branch. This is the equivalent of having the "Old Master" folder open in a new tab.

**Comment by EAWF** [comment]
OK, I trust you.

**Comment by Septem151** [comment]
@EAWF Anytime you need to old code, you can go to https://github.com/EAWF/Bitcoin-Merchants-Toolbox/tree/old-master

Anytime you need to download the files that are within the old-master branch, you can either open the individual file within GitHub and select the Download option, or you can download the entire old-master branch by clicking on the "Download" button at the top-right at https://github.com/EAWF/Bitcoin-Merchants-Toolbox/tree/old-master

**Pull request merged**
